name: "Manuell bygg og publisering generert typescript klient"
on:
  workflow_dispatch:
    inputs:
      disregardCompatFail:
        type: boolean
        description: Aktiver viss publisering skal utførast sjølv om kompilering på ung-brukerdialog-web feiler.
        default: false
        required: true
jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: read
      id-token: write
    uses: navikt/sif-gha-workflows/.github/workflows/maven-build-app-db.yml@main
    with:
      java-version: 25
      build-image: false
      push-image: false
      upload-image: false
      db_schema: ung_sak_unit
      pg_version: 16
      t-2c: "-T1C"
    secrets: inherit

  build-typescript-client:
    name: Build typescript client
    runs-on: ubuntu-latest
    needs: build-app # Only really needed to get the build-version output. Could instead generate that without building if we want to speed things up.
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: navikt/sif-gha-workflows/.github/actions/maven/generate-openapi@main
        id: generate-openapi
        with:
          java-version: 25
          readerToken: ${{ secrets.READER_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          openapiFileName: ung-brukerdialog.openapi.json
      - uses: ./.github/actions/generate-typescript-client
        id: generate-typescript
        with:
          openapiVersion: ${{ steps.generate-openapi.outputs.openapiVersion }}
          patchVersion: ${{ needs.build-app.outputs.build-version }}
      # Upload generated typescript package, so it can be downloaded and published by later job
      - uses: actions/upload-artifact@v6
        id: upload-typescript
        with:
          name: ung-brukerdialog-typescript-client-src
          path: "${{ steps.generate-typescript.outputs.resultDir }}"
          if-no-files-found: error

  check-compat-typescript-client:
    name: Compatibility check typescript client
    runs-on: ubuntu-latest
    needs: [ build-typescript-client ]
    continue-on-error: ${{ inputs.disregardCompatFail }}
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: ung-brukerdialog-typescript-client-src
          path: /tmp/ung-brukerdialog-typescript-client
      - uses: navikt/k9-sak-web/.github/actions/check-compat-typescript-client@master
        with:
          readerToken: ${{ secrets.READER_TOKEN }}
          newClientPath: /tmp/ung-brukerdialog-typescript-client

  publish-typescript-client:
    name: Publish typescript client
    runs-on: ubuntu-latest
    if: github.ref_name == github.event.repository.default_branch
    needs: [check-compat-typescript-client]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/download-artifact@v7
        with:
          name: ung-brukerdialog-typescript-client-src
          path: /tmp/ung-brukerdialog-typescript-client
      - uses: navikt/openapi-ts-clientmaker/extra/actions/publish-typescript-client@v1
        with:
          contentPath: /tmp/ung-brukerdialog-typescript-client
          githubToken: ${{ secrets.GITHUB_TOKEN }}
